### ISSUE TITLE
The texts on the mod selection screen are out of the visible area

### ISSUE THREAD

**Issue by hkBattousai** [EverestAPI/Resources#2]
I can start and run Celest without any problem. Everything is fine. But when I enter the custom map selection screen, the text content is out of screen.

My video options are:
Fullscreen: OFF
Window Scale: 8x
Vertical Sync: ON
Photosensitive Mode: OFF
Screen Shake Effects: ON

Celest version: 1.2.6.1
Everest version: "v.1.830.0-azure"

<img width="1281" alt="SS" src="https://user-images.githubusercontent.com/8620559/56602564-6dd4a480-6606-11e9-8d6c-50a18c369bf0.png">

**Comment by CrazyAccountName** [comment]
I had a similar problem, and it was down to not renaming the level properly, so it displayed the file path which was too long. It might not be that but it looks very similar.

**Comment by PenguinOwl** [comment]
If this is still a problem, please open this issue on the actual Everest repo or bring it up in the discord.
