### ISSUE TITLE
Crashes on "climb"

### ISSUE THREAD

**Issue by Octelly** [EverestAPI/Resources#3]
**Celeste (with Everest installed)** crashes when I choose "climb" in the main menu. This is the exception it throws:
```
--------------------------------
Detailed exception log:
--------------------------------
System.MissingFieldException: Field 'Celeste.AreaModeStats.SingleRunCompleted' not found.
  at Celeste.OuiFileSelect.LoadThread () [0x00075] in <59bc045b8fcb4138a2dafd7521e93558>:0 
  at Celeste.RunThread.RunThreadWithLogging (System.Action method) [0x00002] in <59bc045b8fcb4138a2dafd7521e93558>:0
```

I'm on **Ubuntu 18.04.3 LTS x86_64**. I successfully installed the `mono-devel` package from the official Mono repository, as linked to on https://everestapi.github.io.

A directory called `orig` wasn't present in the game's files before I installed Everest. I succesfully ran `mono MiniInstaller.exe` before I started the game and "mod options" is available in the main menu.

I did not install any mods (yet), but I tried opening a map from Ahorn with no luck.

**Comment by PenguinOwl** [comment]
If this is still a problem, please open this issue on the actual Everest repo or bring it up in the discord.
