### ISSUE TITLE
Problem with installing everest

### ISSUE THREAD

**Issue by Alejo240git** [EverestAPI/Resources#5]
[log.txt](https://github.com/EverestAPI/Resources/files/10778215/log.txt)
[log-sharp.txt](https://github.com/EverestAPI/Resources/files/10778216/log-sharp.txt)
i already oppened celeste onece btw

**Comment by Kalobi** [comment]
Never saw this until today because this isn't the place for Everest installation issues. If you happen to see this message and are still having issues, please make a #modding_help post on the Celeste discord.
